### ISSUE TITLE
Bio Responsiveness Broken!

### ISSUE THREAD

**Issue by charlie-quinn** [charlie-quinn/portfolio-coming-soon#1]
The bio section of my site is responsive on mobile screens and tablet (portrait only).

I'd like the text to align like it does on the tablet portrait screen.
 
![screen shot 2015-09-14 at 2 38 20 pm](https://cloud.githubusercontent.com/assets/6362454/9858416/906b70b8-5aee-11e5-9727-2d647274b883.png)

![screen shot 2015-09-14 at 2 38 38 pm](https://cloud.githubusercontent.com/assets/6362454/9858421/95c92db6-5aee-11e5-907c-0a6046a65eee.png)

Please help! @thomasjbradley

**Comment by thomasjbradley** [comment]
I don't quite understand what you mean... could you draw me a picture or something maybe...

**Comment by charlie-quinn** [comment]
I want the "bio" paragraph to sit underneath my name on tablet-landscape and desktop, like it does on mobile and tablet-portrait. Right now it's too far to the right. I've tried playing with padding/margins, right/left.
See example below:
 
![example](https://cloud.githubusercontent.com/assets/6362454/9861845/fe146dea-5b02-11e5-9d80-ad09395207b8.jpg)

@thomasjbradley

**Comment by thomasjbradley** [comment]
Ahhh... okay.

Try setting the paddings on the left of the text in `rem` instead of `em` that way they'll be consistent between the two different font sizes. Try also removing the `position: absolute`, it may not be necessary.
